### PR TITLE
Extension Azure Stack Edge

### PR DESCRIPTION
**Pull request by rickijen**

### CODE REVIEW

**Comment by rickijen** [comment]
@ganrad please review the new extension for Azure Stack Edge.

**Review by ganrad — CHANGES_REQUESTED** [review]
@rickijen Please remove (/mask) the image credentials (registry name, username, password, email id) from 'values.yaml' file under helm chart folder.  Leaving these values in the file doesn't expose vulnerabilities, its just best practice :-).  Everything else looks good.  Will merge your extension as soon I hear back from you.  Thx.

**Comment by rickijen** [comment]
> @rickijen Please remove (/mask) the image credentials (registry name, username, password, email id) from 'values.yaml' file under helm chart folder. Leaving these values in the file doesn't expose vulnerabilities, its just best practice :-). Everything else looks good. Will merge your extension as soon I hear back from you. Thx.

Sure, updated with sample values for reference.

**Comment by rickijen** [comment]
Added functional architecture diagram to the README.md

**Comment by ganrad** [comment]
Rick, thanks for contributing this extension !

**Pull request merged**
